const $=id=>document.getElementById(id);
const fmt=n=>n==null?'—':Number(n).toLocaleString('es-CO');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const map=L.map('map',{preferCanvas:true,zoomControl:true}).setView([4.55,-75.8],7);
const primary=L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:19,subdomains:'abcd',attribution:'© OpenStreetMap contributors © CARTO'});
const fallback=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'});
primary.addTo(map);let fallbackAdded=false;primary.on('tileerror',()=>{if(!fallbackAdded){fallbackAdded=true;fallback.addTo(map);}});
const markers=L.layerGroup().addTo(map);let markerById=new Map();
const icon={edificio:'🔴',infraestructura:'🔵',zona:'🟠'};
function getFiltered(){const dep=$('department').value,city=$('city').value,type=$('type').value;return DATA.points.filter(p=>(!dep||p.departamento===dep)&&(!city||p.ciudad===city)&&(!type||p.tipo===type));}
function renderMetrics(rows){const filtered=Boolean($('department').value||$('city').value||$('type').value);if(!filtered){const m=DATA.summary;$('metrics').innerHTML=[['Fallecidos',m.fallecidos],['Heridos',m.heridos],['Desaparecidos',m.desaparecidos],['Edificios / sitios reportados',DATA.points.length]].map(x=>`<div class="metric"><div class="n">${fmt(x[1])}</div><div class="l">${x[0]}</div></div>`).join('');$('filterNote').textContent='';return;}const edificios=rows.filter(p=>p.tipo==='edificio').length;const infra=rows.filter(p=>p.tipo==='infraestructura').length;$('metrics').innerHTML=[['Puntos visibles',rows.length],['Edificios reportados',edificios],['Infraestructura',infra],['Ciudades en vista',new Set(rows.map(p=>p.ciudad)).size]].map(x=>`<div class="metric"><div class="n">${fmt(x[1])}</div><div class="l">${x[0]}</div></div>`).join('');$('filterNote').innerHTML='<strong>Vista filtrada:</strong> las cifras de víctimas no se recalculan por ciudad porque las fuentes consultadas no entregan un desglose consistente que permita atribuirlas sin riesgo de error.';}
function populateFilters(){const dep=[...new Set(DATA.points.map(p=>p.departamento))].sort();const cities=[...new Set(DATA.points.map(p=>p.ciudad))].sort();const d=$('department').value,c=$('city').value;$('department').innerHTML='<option value="">Todos</option>'+dep.map(x=>`<option>${esc(x)}</option>`).join('');$('city').innerHTML='<option value="">Todas</option>'+cities.map(x=>`<option>${esc(x)}</option>`).join('');$('department').value=dep.includes(d)?d:'';$('city').value=cities.includes(c)?c:'';}
function focusPoint(id){const p=DATA.points.find(x=>x.id===id);if(!p)return;map.flyTo([p.lat,p.lon],14,{duration:.8});setTimeout(()=>{const mk=markerById.get(id);if(mk)mk.openPopup();},850);}
function render(){populateFilters();$('status').innerHTML=`${esc(DATA.source)} · ${new Date(DATA.updated+'T12:00:00-05:00').toLocaleDateString('es-CO')} · <a href="${DATA.sourceUrl}" target="_blank" rel="noopener">fuente</a>`;renderPoints();}
function renderPoints(){const rows=getFiltered();markers.clearLayers();markerById=new Map();$('points').innerHTML=rows.map(p=>{const mk=L.marker([p.lat,p.lon]).addTo(markers);markerById.set(p.id,mk);mk.bindPopup(`<b>${esc(p.ciudad)} — ${esc(p.tipo)}</b><br>${esc(p.estado)}<br><b>Necesidad:</b> ${esc(p.necesidad)}<br><small>${esc(p.precision)}</small><br><a href="${p.fuenteUrl}" target="_blank" rel="noopener">Fuente: ${esc(p.fuente)}</a>`);return `<button class="point" data-id="${esc(p.id)}" type="button"><b>${icon[p.tipo]||'•'} ${esc(p.ciudad)} · ${esc(p.tipo)}</b><div>${esc(p.estado)}</div><div>${esc(p.necesidad)}</div><div class="badge">${esc(p.precision)}</div><div class="badge">Fuente: ${esc(p.fuente)}</div><span class="go">Ver en el mapa →</span></button>`;}).join('')||'<p>No hay puntos con estos filtros.</p>';$('count').textContent=`${rows.length} puntos`;document.querySelectorAll('.point[data-id]').forEach(b=>b.addEventListener('click',()=>focusPoint(b.dataset.id)));renderMetrics(rows);$('map-loading').style.display='none';if(rows.length>1){const bounds=L.latLngBounds(rows.map(p=>[p.lat,p.lon]));map.fitBounds(bounds.pad(.18),{maxZoom:11,animate:false});}else if(rows.length===1){map.setView([rows[0].lat,rows[0].lon],14);}else map.setView([4.55,-75.8],7);setTimeout(()=>map.invalidateSize({pan:false}),80);setTimeout(()=>map.invalidateSize({pan:false}),500);}
$('department').addEventListener('change',renderPoints);$('city').addEventListener('change',renderPoints);$('type').addEventListener('change',renderPoints);$('reset').addEventListener('click',()=>{$('department').value='';$('city').value='';$('type').value='';renderPoints();});$('locate').addEventListener('click',()=>map.locate({setView:true,maxZoom:13}));map.on('locationerror',()=>alert('No fue posible obtener tu ubicación.'));render();
