const DATA={
summary:{fallecidos:265,heridos:3494,desaparecidos:496,municipios:null,viviendas_averiadas:null,viviendas_destruidas:null,edificios_colapsados:null},
source:'Balance más reciente localizado: Presidencia de Colombia, reportado el 13 de agosto de 2026',
updated:'2026-08-13',
sourceUrl:'https://elpais.com/espana/2026-08-13/exteriores-confirma-un-fallecido-espanol-con-doble-nacionalidad-en-el-terremoto-de-colombia.html',
points:[
 {id:'torres-limonar',ciudad:'Cali',municipio:'Cali',departamento:'Valle del Cauca',tipo:'edificio',estado:'COLAPSO / RESCATE REPORTADO',necesidad:'Búsqueda y rescate. No ingresar ni acercarse sin coordinación oficial.',lat:3.3918,lon:-76.5480,precision:'zona aproximada; coordenada del sitio no confirmada por autoridad en la fuente consultada',fuente:'Reuters, 12/08/2026',fuenteUrl:'https://www.reuters.com/business/environment/search-colombia-earthquake-survivors-stretches-into-third-day-2026-08-12/'},
 {id:'ana-pilar',ciudad:'Cali',municipio:'Cali',departamento:'Valle del Cauca',tipo:'edificio',estado:'COLAPSO REPORTADO',necesidad:'Búsqueda y rescate. No desplazarse al sitio sin coordinación oficial.',lat:3.4236,lon:-76.5460,precision:'zona aproximada de Cuarto de Legua; dirección exacta no verificada',fuente:'El País, 12/08/2026',fuenteUrl:'https://elpais.com/america-colombia/2026-08-12/el-primer-cuerpo-de-rescatistas-internacionales-llega-a-cali-las-posibilidades-de-supervivencia-son-del-20.html'},
 {id:'guadalupe',ciudad:'Cali',municipio:'Cali',departamento:'Valle del Cauca',tipo:'edificio',estado:'DAÑO ESTRUCTURAL GRAVE REPORTADO',necesidad:'Edificio inhabitable; evaluación/rescate coordinado. No ingresar.',lat:3.4155,lon:-76.5485,precision:'ubicación aproximada; la fuente identifica el conjunto pero no aporta coordenadas',fuente:'El País, 11/08/2026',fuenteUrl:'https://elpais.com/america-colombia/2026-08-11/cali-pasa-la-primera-noche-despues-del-terremoto-que-viene-despues-de-esto.html'},
 {id:'hotel-pereira',ciudad:'Pereira',municipio:'Pereira',departamento:'Risaralda',tipo:'edificio',estado:'COLAPSO REPORTADO',necesidad:'Búsqueda y rescate. Zona de escombros; no ingresar ni intervenir sin coordinación.',lat:4.8143,lon:-75.6946,precision:'centro de Pereira; la fuente no permite identificar coordenada exacta del hotel',fuente:'El País, 12/08/2026',fuenteUrl:'https://elpais.com/america-colombia/2026-08-12/sobre-las-ruinas-del-hotel-que-albergaba-a-los-mas-pobres-cientos-de-manos-cavan-sin-ayuda-en-pereira.html'},
 {id:'hospital-quibdo',ciudad:'Quibdó',municipio:'Quibdó',departamento:'Chocó',tipo:'infraestructura',estado:'HOSPITAL AFECTADO / SOBRECUPADO REPORTADO',necesidad:'Atención sanitaria y coordinación institucional; no enviar voluntarios sin instrucción.',lat:5.6956,lon:-76.6610,precision:'ubicación del hospital; el estado de emergencia es reportado por prensa, no es una autorización de acceso',fuente:'El País, 13/08/2026',fuenteUrl:'https://elpais.com/america-colombia/2026-08-13/la-incertidumbre-y-el-temor-se-apoderan-de-quibdo-tras-el-terremoto-es-verdad-que-la-casita-se-va-a-caer.html'},
 {id:'quibdo-comunas',ciudad:'Quibdó',municipio:'Quibdó',departamento:'Chocó',tipo:'zona',estado:'COLAPSOS EN 3 DE 6 COMUNAS REPORTADOS',necesidad:'Evaluación estructural y respuesta oficial. No es un edificio específico.',lat:5.6947,lon:-76.6611,precision:'centro municipal; zona general, no edificio específico',fuente:'El País, 13/08/2026',fuenteUrl:'https://elpais.com/america-colombia/2026-08-13/la-incertidumbre-y-el-temor-se-apoderan-de-quibdo-tras-el-terremoto-es-verdad-que-la-casita-se-va-a-caer.html'},
 {id:'cali-agregado',ciudad:'Cali',municipio:'Cali',departamento:'Valle del Cauca',tipo:'zona',estado:'107 EDIFICIOS COLAPSADOS Y >600 CON DAÑOS SEVEROS REPORTADOS',necesidad:'Información agregada; no identifica cada edificio. No usar como punto de rescate.',lat:3.4516,lon:-76.5320,precision:'centro de Cali; agregado urbano',fuente:'El País, 12/08/2026',fuenteUrl:'https://elpais.com/america-colombia/2026-08-12/el-primer-cuerpo-de-rescatistas-internacionales-llega-a-cali-las-posibilidades-de-supervivencia-son-del-20.html'}
]};
